### ISSUE TITLE
examples/info panic

### ISSUE THREAD

**Issue by pravic** [cogciprocate/ocl#17]
This example raises panic with

> thread `'<main>'` panicked at 'assertion failed: `(left == right)` (left: `4`, right: `8`)', rust-ocl\src\util.rs:196

 on any of following commented function:

```
				print_context_info(&context);
				// print_queue_info(&queue);
				// print_buffer_info(&buffer);
				// print_image_info(&image);
				// print_sampler_info(&sampler);
				print_program_info(&program);
				// print_kernel_info(&kernel);
				// print_event_list_info(&event_list);
				// print_event_info(&event);
```

Windows 7 x64, OCL runtimes: nvidia 1.2, intel 2.0, intel 1.2.

**Comment by c0gent** [comment]
I'm having trouble reproducing this on any of my platform combinations. Are you using the MSVC version of rust by chance?

**Comment by pravic** [comment]
Issue above from the following environment:

> rustc 1.10.0-nightly (8492b6aa4 2016-05-14)
host: i686-pc-windows-msvc

With x86_64 all print functions works well except `print_kernel_info` on intel 1.2 (2.0 works well):

> thread `'<main>'` panicked at 'assertion failed: `(left == right)` (left: `8`, right: `0`)', src\util.rs:179

**Comment by c0gent** [comment]
Ok great, that makes you the first MSVC user of this library I know about :)

I never really got it to work when I tried back in Rust v1.4 or 1.5. I've been wanting to get it running on that platform for a while now.

I'll install on my Windows machine and try to get to the bottom of this issue. I have a good idea of what the problem is.

**Comment by pravic** [comment]
Don't forget to use the rustup, it really help you with testing :)

**Comment by c0gent** [comment]
Cool, will do.

**Comment by c0gent** [comment]
Having trouble getting it to link with OpenCL.dll. Works fine in the GNU/MSYS2 version but MSVC doesn't like me. I've tried copying it to the rust toolchain lib folder and messing with my path but to no avail. I'm not really familiar with the nuances of linking on Windows. Any advice?

**Comment by c0gent** [comment]
ec32f1c0d1de9380f02e7aa1726c46b8676b6d00

Give that a try.

**Comment by pravic** [comment]
Fixed all except the [latest issue](https://github.com/cogciprocate/ocl/issues/17#issuecomment-219310133). It reproducible with x86 and x64 rustc.

**Comment by c0gent** [comment]
@pravic 
Still getting the panic at util.rs::196? Make sure to `cargo update`.

**Comment by pravic** [comment]
src/util.rs:179

**Comment by c0gent** [comment]
For some reason I can't reproduce this with the 32-bit toolchain.

I'm having trouble compiling with x86_64-msvc due to link.exe not being able to locate 'OpenCL.lib'. Any idea where I'm supposed to find or how I can make this file?

The core of the problem, by the way, is almost certainly with a temporary printing function which converts raw bytes from `info` functions into either integers or strings depending on their size. This is a horrible hack and I've just been to lazy to implement it properly because to do so I'll have to manually handle cases for dozens of enum variants. I might have time to do this later this afternoon but I still want to know exactly what is causing the panic you're getting because there may be some other larger issue here.

**Comment by pravic** [comment]
> not being able to locate 'OpenCL.lib'.

It is not a surprise actually, MSVC uses .lib for DLL linking. 

Quick and dirty way is to place .lib to the `target` or `target/deps` path.

The Rusty way is to write a [build script](http://doc.crates.io/build-script.html) which lookups the `%INTELOCLSDKROOT%` environment variable and appends `%INTELOCLSDKROOT%\lib\x86` to the cargo search path list (depending from `TARGET` [of course](http://doc.crates.io/environment-variables.html)).

NVIDIA has its own environment variables too. And I know nothing about AMD.

**Comment by c0gent** [comment]
Ok I'll fiddle around with the x64 stuff later this week. I have multiple machines with various assortments of device platforms so I'll need to come up with a script to deal with that. I currently use the environment variable OCL_DEFAULT_PLATFORM_IDX to set the default platform within ocl so maybe I can come up with something clever that works with that.

I'll have time later today to replace my temporary info printing hack with a proper implementation. If that fixes that panic on your machine we'll call it good for now.

**Comment by c0gent** [comment]
Hopefully 4b228a34f5605d7a0a0d0682d5297cb719d1b3b2 fixes the panic.

Try it out and let me know. It's working on MSVC 32-bit for me.

**Comment by pravic** [comment]
> Program (terse) { KernelNames: 'multiply ', NumDevices: 1, ReferenceCount: 1, Context: Context(0x2ef3b08) }
thread '`<main>`' panicked at 'The size of the source byte vector (0 bytes) does not match the size of the destination type (4 bytes).', src\util.rs:180

```
   3:   0xf46670 - std::panicking::begin_panic_fmt::h484cd47786497f03
   4:   0xf3004e - bytes_into<u32>
                at rust-ocl\<std macros>:8
   5:   0xf0e0ae - from_bytes
                at rust-ocl\src\core\types\enums.rs:1652
   6:   0xf0d7ea - get_kernel_work_group_info<ocl::standard::device::Device>
                at rust-ocl\src\core\functions.rs:1490
   7:   0xf0d37e - wg_info
                at rust-ocl\src\standard\kernel.rs:464
   8:   0xf0ee5c - fmt_wg_info
                at rust-ocl\src\standard\kernel.rs:493
   9:   0xf0f894 - fmt
                at rust-ocl\src\standard\kernel.rs:626
  10:   0xed6865 - fmt<ocl::standard::kernel::Kernel>
                at src\libcore\fmt\mod.rs:1359
  11:   0xf5870d - core::fmt::write::h218cb9026097c841
  12:   0xf4991c - _<io..stdio..Stdout as io..Write>::write_fmt::h9a3625fb6f3b5ee6
  13:   0xf4a238 - std::io::stdio::_print::h5f3493b86d74131b
  14:   0xed630e - print_kernel_info
```

**Comment by c0gent** [comment]
d37ba4d7c2913590be6f832a5e5aeddbe57270cb

Try that.

**Comment by c0gent** [comment]
There are always undocumented implementation specific quirks with these functions. Joy.

**Comment by c0gent** [comment]
Let me know how that fix from yesterday worked when you get a chance. If you get another error shoot me the error/stack trace again and I'll fix it right away. 

As I mentioned there may be a few more weird implementation specific quirks where the OpenCL runtime on your machine returns things slightly differently. The spec is sometimes ambiguous and vendors just kinda all do their own thing. There are variances between generations of devices occasionally too it looks like.

Appreciate your help squashing these. :)

**Comment by pravic** [comment]
See comments to c49c83a.

**Comment by c0gent** [comment]
Try again when you can. I'm going to be working on this lib all day so I'll probably be able to fire fixes right back at you pretty fast.

**Comment by pravic** [comment]
info.exe was chashed (AccessViolation somewhere):

> Looping through avaliable platforms (3):
error: Process didn't exit successfully:

**Comment by c0gent** [comment]
K I'm getting too on msvc, I'll figure it out...

**Comment by c0gent** [comment]
a3040b84e3d582e1fcd099cd7c149b53304c309e, 6c6932b0a538a5e29444955299867fe4024e9c71 should fix.

**Comment by c0gent** [comment]
Shooting you your daily nag. Appreciate your help getting this working on hardware I don't have access to.

**Comment by pravic** [comment]
Hehe. I'll check it later :)

**Comment by pravic** [comment]
crash: http://www.everfall.com/paste/id.php?b5w4gb016bob

**Comment by c0gent** [comment]
9ea4b29c23ab4864153b89f6e9e673506b7357d3

Keep 'em coming :)

**Comment by pravic** [comment]
Works well under x86 & x64 both. Finally :ok_hand:

**Comment by c0gent** [comment]
Excellent.
